def bld(bld):
    bld.ap_library(
        name='AP_ModbusSteering',
        src=[
            'AP_ModbusSteering.cpp',
            'modbus_protocol.c',
        ],
        use=['AP_HAL', 'AP_Param'],
    )
